if (typeof module !== 'undefined' && module.parent) {
    var systemDictionary;
}

systemDictionary = {
    "Lookup services":  {"en": "Lookup services",           "de": "Suche Dienste",          "ru": "Поиск сервисов на устройствах"},
    "Lookup devices":   {"en": "Lookup devices",            "de": "Suche Geräte",           "ru": "Поиск устройств"},
    "UPnP settings":    {"en": "UPnP settings",             "de": "UPnP Einstellungen",     "ru": "UPnP настройки"},
    "Ping settings":    {"en": "Ping settings",             "de": "Ping Einstellungen",     "ru": "Ping настройки"},
    "Use":              {"en": "Use",                       "de": "Benutze",                "ru": "Ипользовать"},
    "Instance":         {"en": "Instance",                  "de": "Instanz",                "ru": "Экземпляр"},
    "Host":             {"en": "Host",                      "de": "Host",                   "ru": "Сервер"},
    "Description":      {"en": "Description",               "de": "Beschreibung",           "ru": "Описание"},
    "Install adapters": {"en": "Install adapters",          "de": "Installiere Adapter",       "ru": "Установить драйвера"},
    "Progress":         {"en": "Progress",                  "de": "Progress",               "ru": "Процесс"},
    "Select language":  {"en": "Select language",           "de": "Sprache:",               "ru": "Язык:"},
    "Select all":       {"en": "Select all",                "de": "Alle auswählen",         "ru": "Отметить все"},
    "Deselect all":     {"en": "Deselect all",              "de": "Nichts auswählen",       "ru": "Снять отметку у всех"},
    "License terms":    {"en": "License terms",             "de": "Lizenzbedingungen",      "ru": "Содержание лицензии"},
    "license agreement": {"en": "license agreement",        "de": "Lizenzvertrag",          "ru": "Лицензионное соглашение"},
    "extended":         {"en": "extended",                  "de": "erweitert",              "ru": "расширено"},
    "Found services":   {"en": "%s services found",         "de": "%s Services gefunden",   "ru": "Сервисов найдено: %s"},
    "Found devices":    {"en": "%s devices found",          "de": "%s Geräte gefunden",     "ru": "Потенциальных устройств найдено: %s"},
    "Show suggested":   {"en": "Show suggested",            "de": "Empfohlene Instanzen",   "ru": "Полезные драйвера"},
    "Required for %s":  {"en": "Required for %s",           "de": "benötigt für %s",        "ru": "необходим для %s"},
    "agree":            {"en": "agree",                     "de": "Einverstanden",          "ru": "Согласен(на)"},
    "not agree":        {"en": "not agree",                 "de": "Nicht einverstanden",    "ru": "Не согласен(на)"},
    "license not agree":    {"en": "Not agree with license!", "de": "Mit der Lizenz nicht einverstanden!",  "ru": "Не согласен(на) с лицензией"},
    "license_checkbox": {
        "en": "I am agree shown license agreement.",
        "de": "Ich bin mit der Lizenz einverstanden.",
        "ru": "Я соглаcен/согласна)"
    },
    "Wizard":               {"en": "Wizard",                "de": "Assistent",              "ru": "Поиск"},
    "Next":                 {"en": "Next",                  "de": "Weiter",                 "ru": "Дальше"},
    "Create instances":     {"en": "Create instances",      "de": "Erzeuge Instanzen",      "ru": "Создать"},
    "Back":                 {"en": "Back",                  "de": "Zurück",                 "ru": "Назад"},
    "Close":                {"en": "Close",                 "de": "Schliessen",             "ru": "Закрыть"},
    "Finish":               {"en": "Finish",                "de": "Fertig",                 "ru": "Закончить"},
    "Settings":             {"en": "Settings",              "de": "Einstellungen",          "ru": "Настройки"},
    "Discover":             {"en": "Discover",              "de": "Suchen",                 "ru": "Поиск"},
    "permissionError":      {"en": "Permission error",      "de": "Zugriffsfehler",         "ru": "Ошибка доступа"},
    "Error":                {"en": "Error",                 "de": "Fehler",                 "ru": "Ошибка"},
    "started":              {"en": "started",               "de": "gestartet",              "ru": "запущен"},
    "wait till installed":  {"en": "installation...",       "de": "Installation...",        "ru": "установка..."},
    "new":                  {"en": "new",                   "de": "neu",                    "ru": "новый"},
    "create instance":      {"en": "pending",               "de": "warten",                 "ru": "ожидание очереди"},
    "Details":              {"en": "Details",               "de": "Details",                "ru": "Детали"},
    "Install package":      {"en": "install package...",    "de": "installiere npm-Paket...", "ru": "Установка пакета..."},
    "canceled":             {"en": "canceled by user",      "de": "vom Anwender abgebrochen", "ru": "отменено пользователем"},
    "Ok":                   {"en": "Ok",                    "de": "Ok",                     "ru": "Ok"},
    "Cancel":               {"en": "Cancel",                "de": "Abbrechen",              "ru": "Отмена"},
    "check parameters":     {"en": "check parameters",      "de": "Einstellungen überprüfen", "ru": "проверка параметров"},
    "Ignore":               {"en": "Ignore",                "de": "Ignorieren",             "ru": "Игнорировать"},
    "Show not only new":    {"en": "Show not only new",     "de": "Zeige nicht nur neue Instanzen", "ru": "Не только новые"},
    "Last scan on %s":      {"en": "Last scan on %s",       "de": "Letze Suche war am %s",  "ru": "Последнее скнирование было %s"},
    "Show all instances":   {"en": "Show all instances",    "de": "Zeige alle Instanzen",   "ru": "Показать все предложения"},
    "for %s":               {"en": "for %s",                "de": "für %s",                 "ru": "для %s"},
    "%s devices":           {"en": "%s devices",            "de": "%s Geräte",              "ru": "устройств - %s"},
    "Error: %s":            {"en": "Error: %s",             "de": "Fehler: %s",             "ru": "Ошибка: %s"},
    "on %s":                {"en": "on %s",                 "de": "auf %s",                 "ru": "на %s"},
    "Please close dialog and open it anew!": {
        "en": "Please close dialog and open it a new!",
        "de": "Bitte Dialogfeld schliessen und erneut öffnen!",
        "ru": "Please close dialog and open it a new!"
    },
    "Some dependencies are not installed": {
        "en": "Some dependencies are not installed",
        "de": "Einige erforderliche Instanzen sind nicht installiert",
        "ru": "Некоторые зависимости не установлены"
    },
    "Unknown error":        {"en": "Unknown error",         "de": "Unbekannter Fehler",     "ru": "Неизвестная ошибка"},
    "Edit parameters for %s": {
        "en": "Required parameters for %s",
        "de": "Einstellungen für %s",
        "ru": "Необходимые настройки для %s"
    },
    "Passwords does not match": {
        "en": "Passwords does not match",
        "de": "Kennwörter sind unterschiedlich",
        "ru": "Пароль и повтор пароля не совпадают"
    },
    "Discovery adapter settings": {
        "en": "Discovery adapter settings",
        "de": "Discovery Einstellungen",
        "ru": "Настройки драйвера Discovery"
    },
    "Discover all possible devices": {
        "en": "Discover all possible devices",
        "de": "Suche alle möglichen Geräte",
        "ru": "поиск всевозможных устройств и сервисов"
    },
    "step1_help1": {
        "en": "Press <b><i>\"Discover\"</i></b> to find devices in your network",
        "de": "Drücke <b><i>\"Suchen\"</i></b> um Geräte im lokalen Netzwerk zu suchen",
        "ru": "Нажать <b><i>\"Поиск устройств\"</i></b> для поиска устройств в вашей сети"
    },
    "step1_help2": {
        "en": "or <b><i>\"Next\"</i></b> to use devices from previous discovery process",
        "de": "oder <b><i>\"Weiter\"</i></b> um die Geräte der vorherigen Suche zu benützen",
        "ru": "или <b><i>\"Дальше\"</i></b> что бы использовать устройства из предудущего поиска"
    },
    "Create instances automatically": {
        "en": "Create instances automatically",
        "de": "Instanzen automatisch erzeugen",
        "ru": "Создать всё автоматически"
    },
    // used in tr-064
    'user': {
        de: 'Benutzerrname',
        en: 'Username',
        ru: 'Имя пользователя'
    },
    // used in tr-064
    'password': {
        de: 'Kennwort',
        en: 'Password',
        ru: 'Пароль'
    },
    // used in tr-064
    'passwordRepeat': {
        de: 'Kennwort wiederholen',
        en: 'Passwort repeat',
        ru: 'Повтор пароля'
    },
    "System settings":      {"en": "System settings",       "de": "Systemeinstellungen",    "ru": "Системные настройки"},
    "System language:":     {"en": "System language:",      "de": "System Sprache:",        "ru": "Системный язык:"},
    "Temperature units:":   {"en": "Temperature units:",    "de": "Temperatureinheit:",    "ru": "Единицы измерения температуры:"},
    "Currency:":            {"en": "Currency:",             "de": "Währung:",               "ru": "Знак валюты:"},
    "Date format:":         {"en": "Date format:",          "de": "Datumsformat:",          "ru": "Формат даты:"},
    "DD.MM.YYYY":           {"en": "DD.MM.YYYY",            "de": "DD.MM.YYYY",             "ru": "ДД.ММ.ГГГГ"},
    "DD.MM.YY":             {"en": "DD.MM.YY",              "de": "DD.MM.YY",               "ru": "ДД.ММ.ГГ"},
    "DD/MM/YYYY":           {"en": "DD/MM/YYYY",            "de": "DD/MM/YYYY",             "ru": "ДД/ММ/ГГГГ"},
    "Float divider:":       {"en": "Float divider:",        "de": "Dezimaltrennzeichen:",          "ru": "Разделитель в числе с плавающей запятой:"},
    "comma":                {"en": "comma",                 "de": "Komma",                  "ru": "запятая"},
    "point":                {"en": "point",                 "de": "Punkt",                  "ru": "точка"},
    "Country:":             {"en": "Country:",              "de": "Land",                  "ru": "Страна:"},
    "City:":                {"en": "City:",                 "de": "Stadt:",                 "ru": "Город:"},
    "Address:":             {"en": "Address:",              "de": "Adresse:",               "ru": "Адрес:"},
    "Latitude:":            {"en": "Latitude:",             "de": "Breitengrad:",           "ru": "Широта:"},
    "Longitude:":           {"en": "Longitude:",            "de": "Längengrad:",            "ru": "Долгота:"},
    "Used only for coordinates detection": {
        "en": "Used only for coordinates detection",
        "de": "Wird nur für Positionssuche verwendet",
        "ru": "Используется только для поиска координат"
    },
    "Find coordinates...":  {"en": "Find coordinates...",   "de": "Koordinaten finden...",  "ru": "Найти координаты..."},
    "Save":                 {"en": "Save",                  "de": "Speichern",              "ru": "Сохранить"},
    "Your home":            {"en": "Your home",             "de": "Dein Haus",              "ru": "Твой дом"},

    "Afghanistan": {"en": "Afghanistan", "de": "Afghanistan", "ru": "Afghanistan"},
    "Albania": {"en": "Albania", "de": "Albania", "ru": "Albania"},
    "Algeria": {"en": "Algeria", "de": "Algeria", "ru": "Algeria"},
    "American Samoa": {"en": "American Samoa", "de": "American Samoa", "ru": "American Samoa"},
    "Andorra": {"en": "Andorra", "de": "Andorra", "ru": "Andorra"},
    "Angola": {"en": "Angola", "de": "Angola", "ru": "Angola"},
    "Anguilla": {"en": "Anguilla", "de": "Anguilla", "ru": "Anguilla"},
    "Antarctica": {"en": "Antarctica", "de": "Antarctica", "ru": "Antarctica"},
    "Antigua and Barbuda": {"en": "Antigua and Barbuda", "de": "Antigua and Barbuda", "ru": "Antigua and Barbuda"},
    "Argentina": {"en": "Argentina", "de": "Argentina", "ru": "Argentina"},
    "Armenia": {"en": "Armenia", "de": "Armenia", "ru": "Armenia"},
    "Aruba": {"en": "Aruba", "de": "Aruba", "ru": "Aruba"},
    "Australia": {"en": "Australia", "de": "Australia", "ru": "Австралия"},
    "Austria": {"en": "Austria", "de": "Österreich", "ru": "Австрия"},
    "Azerbaijan": {"en": "Azerbaijan", "de": "Azerbaijan", "ru": "Azerbaijan"},
    "Bahamas": {"en": "Bahamas", "de": "Bahamas", "ru": "Bahamas"},
    "Bahrain": {"en": "Bahrain", "de": "Bahrain", "ru": "Bahrain"},
    "Bangladesh": {"en": "Bangladesh", "de": "Bangladesh", "ru": "Bangladesh"},
    "Barbados": {"en": "Barbados", "de": "Barbados", "ru": "Barbados"},
    "Belarus": {"en": "Belarus", "de": "Weissrussland", "ru": "Беларуссия"},
    "Belgium": {"en": "Belgium", "de": "Belgium", "ru": "Belgium"},
    "Belize": {"en": "Belize", "de": "Belize", "ru": "Belize"},
    "Benin": {"en": "Benin", "de": "Benin", "ru": "Benin"},
    "Bermuda": {"en": "Bermuda", "de": "Bermuda", "ru": "Bermuda"},
    "Bhutan": {"en": "Bhutan", "de": "Bhutan", "ru": "Bhutan"},
    "Bolivia": {"en": "Bolivia", "de": "Bolivia", "ru": "Bolivia"},
    "Bosnia and Herzegovina": {"en": "Bosnia and Herzegovina", "de": "Bosnia and Herzegovina", "ru": "Bosnia and Herzegovina"},
    "Botswana": {"en": "Botswana", "de": "Botswana", "ru": "Botswana"},
    "Bouvet Island": {"en": "Bouvet Island", "de": "Bouvet Island", "ru": "Bouvet Island"},
    "Brazil": {"en": "Brazil", "de": "Brazil", "ru": "Brazil"},
    "British Indian Ocean Territory": {"en": "British Indian Ocean Territory", "de": "British Indian Ocean Territory", "ru": "British Indian Ocean Territory"},
    "Brunei Darussalam": {"en": "Brunei Darussalam", "de": "Brunei Darussalam", "ru": "Brunei Darussalam"},
    "Bulgaria": {"en": "Bulgaria", "de": "Bulgaria", "ru": "Bulgaria"},
    "Burkina Faso": {"en": "Burkina Faso", "de": "Burkina Faso", "ru": "Burkina Faso"},
    "Burundi": {"en": "Burundi", "de": "Burundi", "ru": "Burundi"},
    "Cambodia": {"en": "Cambodia", "de": "Cambodia", "ru": "Cambodia"},
    "Cameroon": {"en": "Cameroon", "de": "Cameroon", "ru": "Cameroon"},
    "Canada": {"en": "Canada", "de": "Canada", "ru": "Canada"},
    "Cape Verde": {"en": "Cape Verde", "de": "Cape Verde", "ru": "Cape Verde"},
    "Cayman Islands": {"en": "Cayman Islands", "de": "Cayman Islands", "ru": "Cayman Islands"},
    "Central African Republic": {"en": "Central African Republic", "de": "Central African Republic", "ru": "Central African Republic"},
    "Chad": {"en": "Chad", "de": "Chad", "ru": "Chad"},
    "Chile": {"en": "Chile", "de": "Chile", "ru": "Chile"},
    "China": {"en": "China", "de": "China", "ru": "China"},
    "Christmas Island": {"en": "Christmas Island", "de": "Christmas Island", "ru": "Christmas Island"},
    "Colombia": {"en": "Colombia", "de": "Colombia", "ru": "Colombia"},
    "Comoros": {"en": "Comoros", "de": "Comoros", "ru": "Comoros"},
    "Congo": {"en": "Congo", "de": "Congo", "ru": "Congo"},
    "Cook Islands": {"en": "Cook Islands", "de": "Cook Islands", "ru": "Cook Islands"},
    "Costa Rica": {"en": "Costa Rica", "de": "Costa Rica", "ru": "Costa Rica"},
    "Cuba": {"en": "Cuba", "de": "Cuba", "ru": "Cuba"},
    "Cyprus": {"en": "Cyprus", "de": "Cyprus", "ru": "Cyprus"},
    "Czech Republic": {"en": "Czech Republic", "de": "Czech Republic", "ru": "Czech Republic"},
    "Denmark": {"en": "Denmark", "de": "Denmark", "ru": "Denmark"},
    "Djibouti": {"en": "Djibouti", "de": "Djibouti", "ru": "Djibouti"},
    "Dominica": {"en": "Dominica", "de": "Dominica", "ru": "Dominica"},
    "Dominican Republic": {"en": "Dominican Republic", "de": "Dominican Republic", "ru": "Dominican Republic"},
    "East Timor": {"en": "East Timor", "de": "East Timor", "ru": "East Timor"},
    "Ecuador": {"en": "Ecuador", "de": "Ecuador", "ru": "Ecuador"},
    "Egypt": {"en": "Egypt", "de": "Egypt", "ru": "Egypt"},
    "El Salvador": {"en": "El Salvador", "de": "El Salvador", "ru": "El Salvador"},
    "Equatorial Guinea": {"en": "Equatorial Guinea", "de": "Equatorial Guinea", "ru": "Equatorial Guinea"},
    "Eritrea": {"en": "Eritrea", "de": "Eritrea", "ru": "Eritrea"},
    "Estonia": {"en": "Estonia", "de": "Estonia", "ru": "Estonia"},
    "Ethiopia": {"en": "Ethiopia", "de": "Ethiopia", "ru": "Ethiopia"},
    "Faroe Islands": {"en": "Faroe Islands", "de": "Faroe Islands", "ru": "Faroe Islands"},
    "Fiji": {"en": "Fiji", "de": "Fiji", "ru": "Fiji"},
    "Finland": {"en": "Finland", "de": "Finland", "ru": "Finland"},
    "France": {"en": "France", "de": "France", "ru": "France"},
    "French Guiana": {"en": "French Guiana", "de": "French Guiana", "ru": "French Guiana"},
    "French Polynesia": {"en": "French Polynesia", "de": "French Polynesia", "ru": "French Polynesia"},
    "French Southern Territories": {"en": "French Southern Territories", "de": "French Southern Territories", "ru": "French Southern Territories"},
    "Gabon": {"en": "Gabon", "de": "Gabon", "ru": "Gabon"},
    "Gambia": {"en": "Gambia", "de": "Gambia", "ru": "Gambia"},
    "Georgia": {"en": "Georgia", "de": "Georgia", "ru": "Georgia"},
    "Germany": {"en": "Germany", "de": "Deutschland", "ru": "Германия"},
    "Ghana": {"en": "Ghana", "de": "Ghana", "ru": "Ghana"},
    "Gibraltar": {"en": "Gibraltar", "de": "Gibraltar", "ru": "Gibraltar"},
    "Guernsey": {"en": "Guernsey", "de": "Guernsey", "ru": "Guernsey"},
    "Greece": {"en": "Greece", "de": "Greece", "ru": "Greece"},
    "Greenland": {"en": "Greenland", "de": "Greenland", "ru": "Greenland"},
    "Grenada": {"en": "Grenada", "de": "Grenada", "ru": "Grenada"},
    "Guadeloupe": {"en": "Guadeloupe", "de": "Guadeloupe", "ru": "Guadeloupe"},
    "Guam": {"en": "Guam", "de": "Guam", "ru": "Guam"},
    "Guatemala": {"en": "Guatemala", "de": "Guatemala", "ru": "Guatemala"},
    "Guinea": {"en": "Guinea", "de": "Guinea", "ru": "Guinea"},
    "Guyana": {"en": "Guyana", "de": "Guyana", "ru": "Guyana"},
    "Haiti": {"en": "Haiti", "de": "Haiti", "ru": "Haiti"},
    "Heard and Mc Donald Islands": {"en": "Heard and Mc Donald Islands", "de": "Heard and Mc Donald Islands", "ru": "Heard and Mc Donald Islands"},
    "Honduras": {"en": "Honduras", "de": "Honduras", "ru": "Honduras"},
    "Hong Kong": {"en": "Hong Kong", "de": "Hong Kong", "ru": "Hong Kong"},
    "Hungary": {"en": "Hungary", "de": "Hungary", "ru": "Hungary"},
    "Iceland": {"en": "Iceland", "de": "Iceland", "ru": "Iceland"},
    "India": {"en": "India", "de": "India", "ru": "India"},
    "Isle of Man": {"en": "Isle of Man", "de": "Isle of Man", "ru": "Isle of Man"},
    "Indonesia": {"en": "Indonesia", "de": "Indonesia", "ru": "Indonesia"},
    "Iraq": {"en": "Iraq", "de": "Iraq", "ru": "Ирак"},
    "Iran": {"en": "Iran", "de": "Iran", "ru": "Иран"},
    "Ireland": {"en": "Ireland", "de": "Irland", "ru": "Ирландия"},
    "Israel": {"en": "Israel", "de": "Israel", "ru": "Израиль"},
    "Italy": {"en": "Italy", "de": "Italien", "ru": "Италия"},
    "Ivory Coast": {"en": "Ivory Coast", "de": "Ivory Coast", "ru": "Ivory Coast"},
    "Jersey": {"en": "Jersey", "de": "Jersey", "ru": "Jersey"},
    "Jamaica": {"en": "Jamaica", "de": "Jamaica", "ru": "Jamaica"},
    "Japan": {"en": "Japan", "de": "Japan", "ru": "Japan"},
    "Jordan": {"en": "Jordan", "de": "Jordan", "ru": "Jordan"},
    "Kazakhstan": {"en": "Kazakhstan", "de": "Kazakhstan", "ru": "Kazakhstan"},
    "Kenya": {"en": "Kenya", "de": "Kenya", "ru": "Kenya"},
    "Kiribati": {"en": "Kiribati", "de": "Kiribati", "ru": "Kiribati"},
    "Kosovo": {"en": "Kosovo", "de": "Kosovo", "ru": "Kosovo"},
    "Kuwait": {"en": "Kuwait", "de": "Kuwait", "ru": "Kuwait"},
    "Kyrgyzstan": {"en": "Kyrgyzstan", "de": "Kyrgyzstan", "ru": "Kyrgyzstan"},
    "Latvia": {"en": "Latvia", "de": "Latvia", "ru": "Latvia"},
    "Lebanon": {"en": "Lebanon", "de": "Lebanon", "ru": "Lebanon"},
    "Lesotho": {"en": "Lesotho", "de": "Lesotho", "ru": "Lesotho"},
    "Liberia": {"en": "Liberia", "de": "Liberia", "ru": "Liberia"},
    "Libyan Arab Jamahiriya": {"en": "Libyan Arab Jamahiriya", "de": "Libyan Arab Jamahiriya", "ru": "Libyan Arab Jamahiriya"},
    "Liechtenstein": {"en": "Liechtenstein", "de": "Liechtenstein", "ru": "Liechtenstein"},
    "Lithuania": {"en": "Lithuania", "de": "Lithuania", "ru": "Lithuania"},
    "Luxembourg": {"en": "Luxembourg", "de": "Luxembourg", "ru": "Luxembourg"},
    "Macau": {"en": "Macau", "de": "Macau", "ru": "Macau"},
    "Macedonia": {"en": "Macedonia", "de": "Macedonia", "ru": "Macedonia"},
    "Madagascar": {"en": "Madagascar", "de": "Madagascar", "ru": "Madagascar"},
    "Malawi": {"en": "Malawi", "de": "Malawi", "ru": "Malawi"},
    "Malaysia": {"en": "Malaysia", "de": "Malaysia", "ru": "Malaysia"},
    "Maldives": {"en": "Maldives", "de": "Maldives", "ru": "Maldives"},
    "Mali": {"en": "Mali", "de": "Mali", "ru": "Mali"},
    "Malta": {"en": "Malta", "de": "Malta", "ru": "Malta"},
    "Marshall Islands": {"en": "Marshall Islands", "de": "Marshall Islands", "ru": "Marshall Islands"},
    "Martinique": {"en": "Martinique", "de": "Martinique", "ru": "Martinique"},
    "Mauritania": {"en": "Mauritania", "de": "Mauritania", "ru": "Mauritania"},
    "Mauritius": {"en": "Mauritius", "de": "Mauritius", "ru": "Mauritius"},
    "Mayotte": {"en": "Mayotte", "de": "Mayotte", "ru": "Mayotte"},
    "Mexico": {"en": "Mexico", "de": "Mexico", "ru": "Mexico"},
    "Monaco": {"en": "Monaco", "de": "Monaco", "ru": "Monaco"},
    "Mongolia": {"en": "Mongolia", "de": "Mongolia", "ru": "Mongolia"},
    "Montenegro": {"en": "Montenegro", "de": "Montenegro", "ru": "Montenegro"},
    "Montserrat": {"en": "Montserrat", "de": "Montserrat", "ru": "Montserrat"},
    "Morocco": {"en": "Morocco", "de": "Morocco", "ru": "Morocco"},
    "Mozambique": {"en": "Mozambique", "de": "Mozambique", "ru": "Mozambique"},
    "Myanmar": {"en": "Myanmar", "de": "Myanmar", "ru": "Myanmar"},
    "Namibia": {"en": "Namibia", "de": "Namibia", "ru": "Namibia"},
    "Nauru": {"en": "Nauru", "de": "Nauru", "ru": "Nauru"},
    "Nepal": {"en": "Nepal", "de": "Nepal", "ru": "Nepal"},
    "Netherlands": {"en": "Netherlands", "de": "Netherlands", "ru": "Netherlands"},
    "Netherlands Antilles": {"en": "Netherlands Antilles", "de": "Netherlands Antilles", "ru": "Netherlands Antilles"},
    "New Caledonia": {"en": "New Caledonia", "de": "New Caledonia", "ru": "New Caledonia"},
    "New Zealand": {"en": "New Zealand", "de": "New Zealand", "ru": "New Zealand"},
    "Nicaragua": {"en": "Nicaragua", "de": "Nicaragua", "ru": "Nicaragua"},
    "Niger": {"en": "Niger", "de": "Niger", "ru": "Niger"},
    "Nigeria": {"en": "Nigeria", "de": "Nigeria", "ru": "Nigeria"},
    "Niue": {"en": "Niue", "de": "Niue", "ru": "Niue"},
    "Norfolk Island": {"en": "Norfolk Island", "de": "Norfolk Island", "ru": "Norfolk Island"},
    "Northern Mariana Islands": {"en": "Northern Mariana Islands", "de": "Northern Mariana Islands", "ru": "Northern Mariana Islands"},
    "Norway": {"en": "Norway", "de": "Norway", "ru": "Norway"},
    "Oman": {"en": "Oman", "de": "Oman", "ru": "Oman"},
    "Pakistan": {"en": "Pakistan", "de": "Pakistan", "ru": "Pakistan"},
    "Palau": {"en": "Palau", "de": "Palau", "ru": "Palau"},
    "Palestine": {"en": "Palestine", "de": "Palestine", "ru": "Palestine"},
    "Panama": {"en": "Panama", "de": "Panama", "ru": "Panama"},
    "Papua New Guinea": {"en": "Papua New Guinea", "de": "Papua New Guinea", "ru": "Papua New Guinea"},
    "Paraguay": {"en": "Paraguay", "de": "Paraguay", "ru": "Paraguay"},
    "Peru": {"en": "Peru", "de": "Peru", "ru": "Peru"},
    "Philippines": {"en": "Philippines", "de": "Philippines", "ru": "Philippines"},
    "Pitcairn": {"en": "Pitcairn", "de": "Pitcairn", "ru": "Pitcairn"},
    "Poland": {"en": "Poland", "de": "Poland", "ru": "Poland"},
    "Portugal": {"en": "Portugal", "de": "Portugal", "ru": "Portugal"},
    "Puerto Rico": {"en": "Puerto Rico", "de": "Puerto Rico", "ru": "Puerto Rico"},
    "Qatar": {"en": "Qatar", "de": "Qatar", "ru": "Qatar"},
    "Reunion": {"en": "Reunion", "de": "Reunion", "ru": "Reunion"},
    "Romania": {"en": "Romania", "de": "Romania", "ru": "Romania"},
    "Russian Federation": {"en": "Russian Federation", "de": "Russland", "ru": "Россия"},
    "Rwanda": {"en": "Rwanda", "de": "Rwanda", "ru": "Rwanda"},
    "Saint Kitts and Nevis": {"en": "Saint Kitts and Nevis", "de": "Saint Kitts and Nevis", "ru": "Saint Kitts and Nevis"},
    "Saint Lucia": {"en": "Saint Lucia", "de": "Saint Lucia", "ru": "Saint Lucia"},
    "Saint Vincent and the Grenadines": {"en": "Saint Vincent and the Grenadines", "de": "Saint Vincent and the Grenadines", "ru": "Saint Vincent and the Grenadines"},
    "Samoa": {"en": "Samoa", "de": "Samoa", "ru": "Samoa"},
    "San Marino": {"en": "San Marino", "de": "San Marino", "ru": "San Marino"},
    "Sao Tome and Principe": {"en": "Sao Tome and Principe", "de": "Sao Tome and Principe", "ru": "Sao Tome and Principe"},
    "Saudi Arabia": {"en": "Saudi Arabia", "de": "Saudi Arabia", "ru": "Saudi Arabia"},
    "Senegal": {"en": "Senegal", "de": "Senegal", "ru": "Senegal"},
    "Serbia": {"en": "Serbia", "de": "Serbia", "ru": "Serbia"},
    "Seychelles": {"en": "Seychelles", "de": "Seychelles", "ru": "Seychelles"},
    "Sierra Leone": {"en": "Sierra Leone", "de": "Sierra Leone", "ru": "Sierra Leone"},
    "Singapore": {"en": "Singapore", "de": "Singapore", "ru": "Singapore"},
    "Slovakia": {"en": "Slovakia", "de": "Slovakia", "ru": "Slovakia"},
    "Slovenia": {"en": "Slovenia", "de": "Slovenia", "ru": "Slovenia"},
    "Solomon Islands": {"en": "Solomon Islands", "de": "Solomon Islands", "ru": "Solomon Islands"},
    "Somalia": {"en": "Somalia", "de": "Somalia", "ru": "Somalia"},
    "South Africa": {"en": "South Africa", "de": "South Africa", "ru": "South Africa"},
    "South Georgia South Sandwich Islands": {"en": "South Georgia South Sandwich Islands", "de": "South Georgia South Sandwich Islands", "ru": "South Georgia South Sandwich Islands"},
    "Spain": {"en": "Spain", "de": "Spain", "ru": "Spain"},
    "Sri Lanka": {"en": "Sri Lanka", "de": "Sri Lanka", "ru": "Sri Lanka"},
    "Sudan": {"en": "Sudan", "de": "Sudan", "ru": "Sudan"},
    "Suriname": {"en": "Suriname", "de": "Suriname", "ru": "Suriname"},
    "Svalbard and Jan Mayen Islands": {"en": "Svalbard and Jan Mayen Islands", "de": "Svalbard and Jan Mayen Islands", "ru": "Svalbard and Jan Mayen Islands"},
    "Swaziland": {"en": "Swaziland", "de": "Swaziland", "ru": "Swaziland"},
    "Sweden": {"en": "Sweden", "de": "Sweden", "ru": "Sweden"},
    "Switzerland": {"en": "Switzerland", "de": "Schweiz", "ru": "Швейцария"},
    "Syrian Arab Republic": {"en": "Syrian Arab Republic", "de": "Syrian Arab Republic", "ru": "Syrian Arab Republic"},
    "Taiwan": {"en": "Taiwan", "de": "Taiwan", "ru": "Taiwan"},
    "Tajikistan": {"en": "Tajikistan", "de": "Tadschikistan", "ru": "Таджикистан"},
    "Thailand": {"en": "Thailand", "de": "Thailand", "ru": "Thailand"},
    "Togo": {"en": "Togo", "de": "Togo", "ru": "Togo"},
    "Tokelau": {"en": "Tokelau", "de": "Tokelau", "ru": "Tokelau"},
    "Tonga": {"en": "Tonga", "de": "Tonga", "ru": "Tonga"},
    "Trinidad and Tobago": {"en": "Trinidad and Tobago", "de": "Trinidad and Tobago", "ru": "Trinidad and Tobago"},
    "Tunisia": {"en": "Tunisia", "de": "Tunisia", "ru": "Tunisia"},
    "Turkey": {"en": "Turkey", "de": "Turkey", "ru": "Turkey"},
    "Turkmenistan": {"en": "Turkmenistan", "de": "Turkmenistan", "ru": "Turkmenistan"},
    "Turks and Caicos Islands": {"en": "Turks and Caicos Islands", "de": "Turks and Caicos Islands", "ru": "Turks and Caicos Islands"},
    "Tuvalu": {"en": "Tuvalu", "de": "Tuvalu", "ru": "Tuvalu"},
    "Uganda": {"en": "Uganda", "de": "Uganda", "ru": "Uganda"},
    "Ukraine": {"en": "Ukraine", "de": "Ukraine", "ru": "Украина"},
    "United Arab Emirates": {"en": "United Arab Emirates", "de": "United Arab Emirates", "ru": "United Arab Emirates"},
    "United Kingdom": {"en": "United Kingdom", "de": "United Kingdom", "ru": "United Kingdom"},
    "United States": {"en": "United States", "de": "United States", "ru": "United States"},
    "United States minor outlying islands": {"en": "United States minor outlying islands", "de": "United States minor outlying islands", "ru": "United States minor outlying islands"},
    "Uruguay": {"en": "Uruguay", "de": "Uruguay", "ru": "Uruguay"},
    "Uzbekistan": {"en": "Uzbekistan", "de": "Uzbekistan", "ru": "Uzbekistan"},
    "Vanuatu": {"en": "Vanuatu", "de": "Vanuatu", "ru": "Vanuatu"},
    "Vatican City State": {"en": "Vatican City State", "de": "Vatican City State", "ru": "Vatican City State"},
    "Venezuela": {"en": "Venezuela", "de": "Venezuela", "ru": "Venezuela"},
    "Vietnam": {"en": "Vietnam", "de": "Vietnam", "ru": "Vietnam"},
    "Wallis and Futuna Islands": {"en": "Wallis and Futuna Islands", "de": "Wallis and Futuna Islands", "ru": "Wallis and Futuna Islands"},
    "Western Sahara": {"en": "Western Sahara", "de": "Western Sahara", "ru": "Western Sahara"},
    "Yemen": {"en": "Yemen", "de": "Yemen", "ru": "Yemen"},
    "Zaire": {"en": "Zaire", "de": "Zaire", "ru": "Zaire"},
    "Zambia": {"en": "Zambia", "de": "Zambia", "ru": "Zambia"},
    "Zimbabwe": {"en": "Zimbabwe", "de": "Zimbabwe", "ru": "Zimbabwe"}
};

if (typeof module !== 'undefined' && module.parent) {
    function translate(lang, word, arg1, arg2) {
        if (systemDictionary[word]) {
            word = systemDictionary[word][lang] || systemDictionary[word].en || word;
        }
        word = word.replace('%s', arg1);
        word = word.replace('%s', arg2);
        return word;
    }
    module.exports = {
        words:    systemDictionary,
        translate: translate
    };
}
